In [40]:
import pandas as pd

In [41]:
df = pd.read_csv("loan_approval_data.csv")

In [42]:
df

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
0,1.0,17795.0,1387.0,Salaried,51.0,Married,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,84.0,Personal,Urban,Not Graduate,Female,Private,No
1,2.0,2860.0,2679.0,Salaried,46.0,Married,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,NaN,Car,Semiurban,Graduate,NaN,Private,No
2,3.0,7390.0,2106.0,Salaried,25.0,Single,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,72.0,NaN,Urban,NaN,Female,Government,Yes
3,4.0,13964.0,8173.0,Salaried,40.0,Married,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,60.0,Business,Rural,Graduate,Female,Government,No
4,5.0,13284.0,4223.0,Self-employed,31.0,Single,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,72.0,Car,NaN,Graduate,Male,Private,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996.0,NaN,9092.0,Salaried,58.0,Married,0.0,557.0,0.0,0.59,5370.0,43563.0,8311.0,72.0,Personal,NaN,Not Graduate,Male,Unemployed,No
996,997.0,3279.0,6356.0,Self-employed,58.0,Married,1.0,646.0,3.0,0.19,NaN,18361.0,22563.0,12.0,Business,Urban,Graduate,Female,Government,No
997,998.0,15192.0,8433.0,Contract,48.0,Single,1.0,666.0,1.0,0.40,8581.0,41335.0,16203.0,24.0,Home,Rural,Graduate,Male,MNC,No
998,999.0,9083.0,7380.0,Unemployed,50.0,Single,1.0,748.0,3.0,0.31,13491.0,8933.0,10290.0,36.0,Personal,Urban,Graduate,Male,Private,Yes
999,1000.0,13093.0,2385.0,Salaried,23.0,Married,1.0,613.0,3.0,0.32,12436.0,25816.0,35818.0,48.0,Personal,Semiurban,Graduate,NaN,Private,No

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Applicant_ID        950 non-null    float64
 1   Applicant_Income    950 non-null    float64
 2   Coapplicant_Income  950 non-null    float64
 3   Employment_Status   950 non-null    object
 4   Age                 950 non-null    float64
 5   Marital_Status      950 non-null    object
 6   Dependents          950 non-null    float64
 7   Credit_Score        950 non-null    float64
 8   Existing_Loans      950 non-null    float64
 9   DTI_Ratio           950 non-null    float64
 10  Savings             950 non-null    float64
 11  Collateral_Value    950 non-null    float64
 12  Loan_Amount         950 non-null    float64
 13  Loan_Term           950 non-null    float64
 14  Loan_Purpose        950 non-null    object
 15  Property_Area       950 non-null    object
 16  Education_Level     950 non-null    object
 17  Gender              950 non-null    object
 18  Employer_Category   950 non-null    object
 19  Loan_Approved       950 non-null    object
dtypes: float64(12), object(8)
memory usage: 156.4+ KB

In [44]:
df.describe()

,Applicant_ID,Applicant_Income,Coapplicant_Income,Age,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term
count,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000
mean,501.220000,10852.571579,5082.455789,39.971579,1.474737,676.033684,1.950526,0.347263,9940.452632,24802.792632,20522.825263,48.000000
std,289.608451,5061.632859,2943.161570,11.139797,1.105067,71.346015,1.406246,0.144341,5860.736885,14345.696031,11504.142575,24.245322
min,1.000000,2009.000000,1.000000,21.000000,0.000000,550.000000,0.000000,0.100000,65.000000,36.000000,1015.000000,12.000000
25%,250.250000,6730.750000,2472.750000,30.250000,1.000000,616.250000,1.000000,0.220000,4760.250000,12698.250000,9806.250000,24.000000
50%,499.500000,10548.000000,5205.500000,40.000000,1.000000,678.000000,2.000000,0.340000,9880.500000,24321.000000,21210.500000,48.000000
75%,752.750000,15190.000000,7620.750000,49.000000,2.000000,737.000000,3.000000,0.480000,15074.500000,36947.000000,30263.000000,72.000000
max,1000.000000,19988.000000,9996.000000,59.000000,3.000000,799.000000,4.000000,0.600000,19996.000000,49954.000000,39995.000000,84.000000

In [45]:
df.sample(10)

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
475,476.0,6312.0,3389.0,Self-employed,54.0,Married,2.0,551.0,3.0,0.28,9596.0,9643.0,NaN,72.0,Home,Rural,Graduate,Male,Business,No
573,574.0,14338.0,6276.0,NaN,39.0,Single,2.0,NaN,1.0,0.25,3367.0,8851.0,2902.0,60.0,Home,Semiurban,Graduate,Female,MNC,Yes
859,860.0,12380.0,9732.0,Unemployed,46.0,Married,1.0,704.0,2.0,0.58,19249.0,38969.0,9253.0,84.0,Education,Semiurban,Graduate,Female,Private,No
403,404.0,NaN,4473.0,Salaried,27.0,Married,1.0,570.0,3.0,0.17,7041.0,42432.0,16739.0,60.0,Home,Semiurban,Not Graduate,Female,Private,No
630,631.0,13637.0,891.0,Salaried,35.0,Married,2.0,792.0,1.0,0.42,1909.0,34964.0,10759.0,24.0,Education,Rural,Graduate,Male,Government,No
764,765.0,11865.0,4616.0,Contract,47.0,Married,2.0,687.0,3.0,0.60,2970.0,20927.0,9968.0,84.0,Personal,Urban,Not Graduate,Female,Unemployed,No
351,352.0,10130.0,9098.0,Salaried,45.0,Single,3.0,651.0,0.0,NaN,329.0,35367.0,20739.0,24.0,Home,Semiurban,Graduate,Male,Business,Yes
222,223.0,7699.0,824.0,Salaried,45.0,Married,1.0,665.0,3.0,0.42,18321.0,2274.0,11363.0,NaN,Education,Rural,Not Graduate,Male,Unemployed,No
113,114.0,18198.0,5604.0,Self-employed,40.0,Married,2.0,634.0,1.0,0.60,4019.0,48384.0,31204.0,48.0,Education,Semiurban,Graduate,Female,Private,No
624,625.0,8254.0,9110.0,Salaried,52.0,Married,1.0,566.0,1.0,0.23,6572.0,NaN,26957.0,12.0,Car,Semiurban,Graduate,Female,Private,No

In [46]:
df['Applicant_ID'].nunique()

950

In [47]:
df['Applicant_ID'].duplicated().sum()

np.int64(49)

In [48]:
missing = df['Applicant_ID'].isnull()

start = int(df['Applicant_ID'].max()) + 1

df.loc[missing, 'Applicant_ID'] = range(
    start,
    start + missing.sum()
)

In [49]:
cols = ['Applicant_Income', 'Coapplicant_Income', 'Age','Dependents','Credit_Score','Existing_Loans','DTI_Ratio','Savings','Collateral_Value','Loan_Amount','Loan_Term']
df[cols] = df[cols].fillna(df[cols].mean())

In [50]:
df['Employment_Status'] = df['Employment_Status'].fillna('Unknown')
df['Marital_Status'] = df['Marital_Status'].fillna('Unknown')
df['Loan_Purpose'] = df['Loan_Purpose'].fillna('Unknown')
df['Property_Area'] = df['Property_Area'].fillna('Unknown')
df['Education_Level'] = df['Education_Level'].fillna('Unknown')
df['Gender'] = df['Gender'].fillna('Unknown')
df['Employer_Category'] = df['Employer_Category'].fillna('Unkown')

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Applicant_ID        1000 non-null   float64
 1   Applicant_Income    1000 non-null   float64
 2   Coapplicant_Income  1000 non-null   float64
 3   Employment_Status   1000 non-null   object
 4   Age                 1000 non-null   float64
 5   Marital_Status      1000 non-null   object
 6   Dependents          1000 non-null   float64
 7   Credit_Score        1000 non-null   float64
 8   Existing_Loans      1000 non-null   float64
 9   DTI_Ratio           1000 non-null   float64
 10  Savings             1000 non-null   float64
 11  Collateral_Value    1000 non-null   float64
 12  Loan_Amount         1000 non-null   float64
 13  Loan_Term           1000 non-null   float64
 14  Loan_Purpose        1000 non-null   object
 15  Property_Area       1000 non-null   object
 16  Education_Level     1000 non-null   object
 17  Gender              1000 non-null   object
 18  Employer_Category   1000 non-null   object
 19  Loan_Approved       950 non-null    object
dtypes: float64(12), object(8)
memory usage: 156.4+ KB

In [52]:
df = df.dropna(subset=['Loan_Approved'])

In [53]:
df.isnull().sum()

Applicant_ID          0
Applicant_Income      0
Coapplicant_Income    0
Employment_Status     0
Age                   0
Marital_Status        0
Dependents            0
Credit_Score          0
Existing_Loans        0
DTI_Ratio             0
Savings               0
Collateral_Value      0
Loan_Amount           0
Loan_Term             0
Loan_Purpose          0
Property_Area         0
Education_Level       0
Gender                0
Employer_Category     0
Loan_Approved         0
dtype: int64

In [54]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, LabelEncoder

In [55]:
x_train, x_test, y_train, y_test = train_test_split(
    df.drop(columns=['Loan_Approved']),
    df['Loan_Approved'],
    test_size=0.2,
    random_state=42
)

In [56]:
x_train.sample(5)

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category
480,481.0,7301.0,207.0,Salaried,42.000000,Married,0.000000,566.0,2.0,0.57,17715.0,8554.0,3369.000000,12.0,Car,Semiurban,Graduate,Female,Private
767,768.0,7287.0,9852.0,Self-employed,39.971579,Married,2.000000,711.0,4.0,0.35,17145.0,9032.0,5674.000000,72.0,Business,Semiurban,Graduate,Male,MNC
678,679.0,10172.0,1388.0,Self-employed,41.000000,Married,1.474737,768.0,4.0,0.15,8953.0,24908.0,20522.825263,72.0,Car,Rural,Graduate,Female,Private
958,959.0,16295.0,9074.0,Self-employed,37.000000,Single,3.000000,738.0,4.0,0.44,19871.0,21446.0,37212.000000,12.0,Business,Urban,Graduate,Male,Unemployed
511,512.0,7645.0,6078.0,Contract,45.000000,Married,1.000000,561.0,2.0,0.38,565.0,23259.0,27926.000000,84.0,Personal,Urban,Graduate,Male,Private

In [57]:
x_train['Employment_Status'].value_counts()

Employment_Status
Salaried         363
Contract         163
Self-employed    137
Unemployed        65
Unknown           32
Name: count, dtype: int64

In [58]:
mapping = {
    'Salaried': 1,
    'Contract': 1,
    'Self-employed': 1,
    'Unemployed': 0,
    'Unknown': 0
}

x_train['Employment_Status'] = x_train['Employment_Status'].map(mapping)
x_test['Employment_Status'] = x_test['Employment_Status'].map(mapping)

In [59]:
x_train['Marital_Status'].value_counts()

Marital_Status
Married    454
Single     264
Unknown     42
Name: count, dtype: int64

In [60]:
mapping = {
    'Single': 1,
    'Married': 0,
    'Unknown': 0
}

x_train['Marital_Status'] = x_train['Marital_Status'].map(mapping)
x_test['Marital_Status'] = x_test['Marital_Status'].map(mapping)

In [61]:
x_train.head()

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category
985,986.0,10705.0,7898.0,1,33.0,1,1.0,704.0,4.0,0.55,569.000000,2654.0,11524.0,84.0,Home,Rural,Graduate,Female,Private
299,300.0,10173.0,2808.0,1,25.0,0,0.0,745.0,3.0,0.22,18055.000000,3838.0,22033.0,24.0,Car,Urban,Graduate,Male,Business
571,572.0,7997.0,3432.0,1,53.0,1,1.0,750.0,4.0,0.52,9940.452632,31736.0,25102.0,36.0,Education,Urban,Graduate,Male,Private
282,283.0,14249.0,4311.0,1,24.0,1,2.0,785.0,4.0,0.38,2284.000000,26754.0,39247.0,48.0,Home,Urban,Graduate,Female,MNC
112,113.0,3059.0,1750.0,1,49.0,0,0.0,770.0,4.0,0.13,15456.000000,5067.0,6695.0,72.0,Car,Rural,Graduate,Male,Government

In [62]:
x_train['Loan_Purpose'].value_counts()

Loan_Purpose
Business     155
Home         151
Car          148
Personal     136
Education    132
Unknown       38
Name: count, dtype: int64

In [65]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

encoded_train = encoder.fit_transform(x_train[['Loan_Purpose']])
encoded_test = encoder.transform(x_test[['Loan_Purpose']])

x_train[encoder.get_feature_names_out()] = encoded_train
x_test[encoder.get_feature_names_out()] = encoded_test

x_train.drop(columns=['Loan_Purpose'], inplace=True)
x_test.drop(columns=['Loan_Purpose'], inplace=True)

In [66]:
x_train.head()

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,...,Property_Area,Education_Level,Gender,Employer_Category,Loan_Purpose_Business,Loan_Purpose_Car,Loan_Purpose_Education,Loan_Purpose_Home,Loan_Purpose_Personal,Loan_Purpose_Unknown
985,986.0,10705.0,7898.0,1,33.0,1,1.0,704.0,4.0,0.55,...,Rural,Graduate,Female,Private,0.0,0.0,0.0,1.0,0.0,0.0
299,300.0,10173.0,2808.0,1,25.0,0,0.0,745.0,3.0,0.22,...,Urban,Graduate,Male,Business,0.0,1.0,0.0,0.0,0.0,0.0
571,572.0,7997.0,3432.0,1,53.0,1,1.0,750.0,4.0,0.52,...,Urban,Graduate,Male,Private,0.0,0.0,1.0,0.0,0.0,0.0
282,283.0,14249.0,4311.0,1,24.0,1,2.0,785.0,4.0,0.38,...,Urban,Graduate,Female,MNC,0.0,0.0,0.0,1.0,0.0,0.0
112,113.0,3059.0,1750.0,1,49.0,0,0.0,770.0,4.0,0.13,...,Rural,Graduate,Male,Government,0.0,1.0,0.0,0.0,0.0,0.0

In [70]:
df['Education_Level'].value_counts()

Education_Level
Graduate        638
Not Graduate    265
Unknown          47
Name: count, dtype: int64

In [68]:
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

train = encoder.fit_transform(x_train[['Property_Area']])
test = encoder.transform(x_test[['Property_Area']])

x_train[encoder.get_feature_names_out()] = train
x_test[encoder.get_feature_names_out()] = test

x_train.drop(columns='Property_Area', inplace=True)
x_test.drop(columns='Property_Area', inplace=True)

In [71]:
mapping = {
    'Graduate': 1,
    'Not Graduate': 0,
    'Unknown': 0
}

x_train['Education_Level'] = x_train['Education_Level'].map(mapping)
x_test['Education_Level'] = x_test['Education_Level'].map(mapping)

In [73]:
mapping = {
    'Male': 1,
    'Female': 0,
    'Unknown': 0
}

x_train['Gender'] = x_train['Gender'].map(mapping)
x_test['Gender'] = x_test['Gender'].map(mapping)

In [75]:
df['Employer_Category'].value_counts()

Employer_Category
Private       351
Government    191
MNC           136
Business      130
Unemployed     95
Unkown         47
Name: count, dtype: int64

In [76]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

train = encoder.fit_transform(x_train[['Employer_Category']])
test = encoder.transform(x_test[['Employer_Category']])

x_train[encoder.get_feature_names_out()] = train
x_test[encoder.get_feature_names_out()] = test

x_train.drop(columns='Employer_Category', inplace=True)
x_test.drop(columns='Employer_Category', inplace=True)

In [77]:
x_train.head()

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,...,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Unknown,Property_Area_Urban,Employer_Category_Business,Employer_Category_Government,Employer_Category_MNC,Employer_Category_Private,Employer_Category_Unemployed,Employer_Category_Unkown
985,986.0,10705.0,7898.0,1,33.0,1,1.0,704.0,4.0,0.55,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
299,300.0,10173.0,2808.0,1,25.0,0,0.0,745.0,3.0,0.22,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
571,572.0,7997.0,3432.0,1,53.0,1,1.0,750.0,4.0,0.52,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
282,283.0,14249.0,4311.0,1,24.0,1,2.0,785.0,4.0,0.38,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
112,113.0,3059.0,1750.0,1,49.0,0,0.0,770.0,4.0,0.13,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [78]:
x_test.head()

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,...,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Unknown,Property_Area_Urban,Employer_Category_Business,Employer_Category_Government,Employer_Category_MNC,Employer_Category_Private,Employer_Category_Unemployed,Employer_Category_Unkown
205,206.0,8295.0,9155.000000,1,51.0,0,1.0,712.0,4.0,0.29,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
978,979.0,6425.0,5082.455789,0,45.0,1,0.0,669.0,0.0,0.42,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
728,729.0,6324.0,7151.000000,0,40.0,0,2.0,616.0,1.0,0.57,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
839,840.0,5756.0,9424.000000,0,49.0,0,1.0,705.0,1.0,0.56,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
919,920.0,18241.0,9325.000000,1,56.0,0,1.0,652.0,4.0,0.53,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0

In [79]:
y_train.value_counts()

Loan_Approved
No     523
Yes    237
Name: count, dtype: int64

In [81]:
mapping = {
    'Yes': 1,
    'No': 0
}

y_train = y_train.map(mapping)
y_test = y_test.map(mapping)

In [82]:
y_train.head()

985    0
299    1
571    0
282    1
112    0
Name: Loan_Approved, dtype: int64

In [83]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 760 entries, 985 to 105
Data columns (total 32 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Applicant_ID                  760 non-null    float64
 1   Applicant_Income              760 non-null    float64
 2   Coapplicant_Income            760 non-null    float64
 3   Employment_Status             760 non-null    int64
 4   Age                           760 non-null    float64
 5   Marital_Status                760 non-null    int64
 6   Dependents                    760 non-null    float64
 7   Credit_Score                  760 non-null    float64
 8   Existing_Loans                760 non-null    float64
 9   DTI_Ratio                     760 non-null    float64
 10  Savings                       760 non-null    float64
 11  Collateral_Value              760 non-null    float64
 12  Loan_Amount                   760 non-null    float64
 13  Loan_Term                     760 non-null    float64
 14  Education_Level               760 non-null    int64
 15  Gender                        760 non-null    int64
 16  Loan_Purpose_Business         760 non-null    float64
 17  Loan_Purpose_Car              760 non-null    float64
 18  Loan_Purpose_Education        760 non-null    float64
 19  Loan_Purpose_Home             760 non-null    float64
 20  Loan_Purpose_Personal         760 non-null    float64
 21  Loan_Purpose_Unknown          760 non-null    float64
 22  Property_Area_Rural           760 non-null    float64
 23  Property_Area_Semiurban       760 non-null    float64
 24  Property_Area_Unknown         760 non-null    float64
 25  Property_Area_Urban           760 non-null    float64
 26  Employer_Category_Business    760 non-null    float64
 27  Employer_Category_Government  760 non-null    float64
 28  Employer_Category_MNC         760 non-null    float64
 29  Employer_Category_Private     760 non-null    float64
 30  Employer_Category_Unemployed  760 non-null    float64
 31  Employer_Category_Unkown      760 non-null    float64
dtypes: float64(28), int64(4)
memory usage: 195.9 KB

In [84]:
x_train.describe()

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,...,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Unknown,Property_Area_Urban,Employer_Category_Business,Employer_Category_Government,Employer_Category_MNC,Employer_Category_Private,Employer_Category_Unemployed,Employer_Category_Unkown
count,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,...,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000
mean,523.584211,10799.972188,5009.474821,0.872368,40.327377,0.347368,1.491400,676.554360,1.938316,0.348683,...,0.289474,0.194737,0.046053,0.469737,0.127632,0.207895,0.147368,0.373684,0.100000,0.043421
std,307.846596,4977.468197,2882.710467,0.333899,10.770487,0.476448,1.083910,69.118642,1.367899,0.141317,...,0.453817,0.396259,0.209737,0.499412,0.333899,0.406068,0.354706,0.484100,0.300198,0.203937
min,1.000000,2009.000000,1.000000,0.000000,21.000000,0.000000,0.000000,550.000000,0.000000,0.100000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,248.750000,6844.750000,2658.250000,1.000000,32.000000,0.000000,1.000000,620.000000,1.000000,0.230000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,524.500000,10852.571579,5082.455789,1.000000,39.971579,0.000000,1.474737,676.033684,2.000000,0.347263,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,793.250000,14920.000000,7439.250000,1.000000,49.000000,1.000000,2.000000,735.000000,3.000000,0.470000,...,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
max,1049.000000,19988.000000,9996.000000,1.000000,59.000000,1.000000,3.000000,799.000000,4.000000,0.600000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [85]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [90]:
x_train_scaled[:1]

array([[ 1.50308731, -0.01909299,  1.00267697,  0.38249794, -0.6807679 ,
         1.37068883, -0.45365735,  0.39734163,  1.50818284,  1.42552094,
        -1.6430017 , -1.57847857, -0.79540663,  1.54201937,  0.69597055,
        -1.16003406, -0.5061604 , -0.4917622 , -0.45846601,  2.00826108,
        -0.46684978, -0.22941573,  1.5666989 , -0.4917622 , -0.21971769,
        -0.94119928, -0.38249794, -0.51230701, -0.41573971,  1.29462595,
        -0.33333333, -0.21305404]])

In [95]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

model = KNeighborsClassifier()

params = {
    'n_neighbors': [3, 5, 7, 9, 11, 13, 15, 17, 19]
}
                      
grid = GridSearchCV(
    estimator=model,
    param_grid=params,
    cv=5
)


grid.fit(x_train_scaled, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [3, 5, 7, 9, 11, 13, 15, 17, 19]})

In [96]:
print(grid.best_params_)
print(grid.best_score_)

{'n_neighbors': 17}
0.7526315789473685

In [101]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

y_pred = grid.predict(x_test_scaled)

In [99]:
print('accuracy_score: ', accuracy_score(y_test, y_pred))
print('precision_score: ', precision_score(y_test, y_pred))
print('recall_score: ', recall_score(y_test, y_pred))

accuracy_score:  0.7526315789473684
precision_score:  0.75
recall_score:  0.3442622950819672

In [103]:
print(confusion_matrix(y_test, y_pred))

[[122   7]
 [ 40  21]]

In [104]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(x_train_scaled, y_train)

LogisticRegression()

In [105]:
y_pred_lr = lr.predict(x_test_scaled)

In [106]:
print('accuracy_score: ', accuracy_score(y_test, y_pred_lr))
print('precision_score: ', precision_score(y_test, y_pred_lr))
print('recall_score: ', recall_score(y_test, y_pred_lr))

accuracy_score:  0.8947368421052632
precision_score:  0.8727272727272727
recall_score:  0.7868852459016393

In [108]:
print(confusion_matrix(y_test, y_pred_lr))

[[122   7]
 [ 13  48]]